let score=0,time=25,timer=null,spawnTimer=null,playing=false;
const st=$('#stage'),sc=$('#score'),tm=$('#time'),ov=$('#overlay'),hint=$('#hint');
$('#play').onclick=()=>{startAudio?.();startGame()};
function resetGame(){clearInterval(timer);clearTimeout(spawnTimer);playing=false;score=0;time=25;sc.textContent='0';tm.textContent='25';st.querySelectorAll('.butterfly').forEach(e=>e.remove());ov.style.display='grid';ov.querySelector('h3').textContent='Ready?';ov.querySelector('p').textContent='Catch them all!';hint.textContent='Tap a butterfly when you see one!'}
function stopGame(){if(playing){clearInterval(timer);clearTimeout(spawnTimer);playing=false}}
function startGame(){resetGame();ov.style.display='none';playing=true;spawn();timer=setInterval(()=>{time--;tm.textContent=time;if(time<=0)finish(false)},1000)}
function spawn(){if(!playing)return;let b=document.createElement('button');b.className='butterfly';b.textContent=['🦋','🦋','🌸','🦋'][Math.floor(Math.random()*4)];b.setAttribute('aria-label','Catch butterfly');b.style.left=5+Math.random()*88+'%';b.style.top=17+Math.random()*68+'%';b.style.animationDuration=(.65+Math.random()*.65)+'s';b.onclick=()=>{if(!playing)return;score++;sc.textContent=score;pop(b);if(navigator.vibrate)navigator.vibrate(10);if(score>=8)finish(true);else spawnTimer=setTimeout(spawn,90)};st.appendChild(b)}
function pop(b){b.animate([{transform:'scale(1)'},{transform:'scale(1.5) rotate(15deg)',opacity:.75},{transform:'scale(.15)',opacity:0}],{duration:190,easing:'cubic-bezier(.2,.8,.2,1)'});setTimeout(()=>b.remove(),180)}
function finish(win){playing=false;clearInterval(timer);clearTimeout(spawnTimer);st.querySelectorAll('.butterfly').forEach(e=>e.remove());if(win){hint.textContent='Perfect! You caught them all. 💗';setTimeout(()=>{S('final');celebrateSound();confetti()},550)}else{hint.textContent="Time's up! Give it another try 🐱";ov.style.display='grid';ov.querySelector('h3').textContent='So close!';ov.querySelector('p').textContent='Try again and catch all 8.'}}
function celebrateSound(){try{const A=window.AudioContext||window.webkitAudioContext,a=new A();[523,659,784,1047,1318,1047,1568].forEach((f,i)=>{let o=a.createOscillator(),g=a.createGain(),t=a.currentTime+i*.09;o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(.08,t+.025);g.gain.exponentialRampToValueAtTime(.001,t+.42);o.connect(g).connect(a.destination);o.start(t);o.stop(t+.45)})}catch(e){}}
function confetti(){for(let i=0;i<80;i++){const z=document.createElement('span');z.textContent=['♡','✿','✦','•','🎀','🌸'][i%6];z.style.cssText=`position:fixed;z-index:60;left:50%;top:47%;pointer-events:none;font-size:${12+Math.random()*22}px;color:${['#ed8eb4','#d8a4ed','#f2b4cb','#f5a3bf'][i%4]}`;document.body.appendChild(z);z.animate([{transform:'translate(-50%,-50%) scale(.2) rotate(0)',opacity:1},{transform:`translate(${(Math.random()-.5)*760}px,${(Math.random()-.12)*720}px) rotate(${Math.random()*900-450}deg)`,opacity:0}],{duration:1300+Math.random()*1100,easing:'cubic-bezier(.2,.8,.2,1)'});setTimeout(()=>z.remove(),2600)}}
resetGame();
